esphome:
  name: regensensor
  platform: esp32
  board: esp32dev

wifi:
  ssid: "your_wifi_ssid"
  password: "your_wifi_password"

logger:

api:
  password: "your_api_password"

ota:
  password: "your_ota_password"

sensor:
  - platform: adc
    pin: GPIO34  # ADC Pin für die Messung
    name: "Regensensor Feuchtigkeit"
    update_interval: never  # Kein regelmäßiges Update, wird manuell gesteuert
    attenuation: 11db
    id: regensensor_feuchtigkeit
    filters:
      - multiply: 3.3  # Korrekturfaktor, je nach Spannungsteiler
      - sliding_window_moving_average:
          window_size: 15  # Mittelwert über 15 Sekunden
          send_every: 15s  # Alle 15 Sekunden neuen Mittelwert senden
      - delta: 0.01  # Verhindert unnötige Updates bei minimalen Änderungen

binary_sensor:
  - platform: template
    name: "Regensensor Status"
    id: regensensor_status
    lambda: |-
      if (id(regensensor_feuchtigkeit).state < 1.65) {
        // Wenn Feuchtigkeit erkannt wird, weniger häufig messen
        id(messintervall).set_interval(300s);  // Alle 5 Minuten messen
        return true;  // Regen
      } else {
        // Wenn es trocken ist, sehr häufig messen
        id(messintervall).set_interval(10s);  // Alle 10 Sekunden messen
        return false;  // Trocken
      }
    filters:
      - delayed_on: 10s  # Verzögert das Umschalten zu "Regen" um 10 Sekunden
      - delayed_off: 30s # Verzögert das Umschalten zu "Trocken" um 30 Sekunden
    device_class: moisture  # Zeigt in Home Assistant "Feuchtigkeit" an

interval:
  - interval: 10s
    then:
      - component.update: regensensor_feuchtigkeit
    id: messintervall  # ID für dynamische Anpassung des Messintervalls
