substitutions:
  name: Wetterstation
  friendly_name: "Wetterstation"
  
  # Widerstandswert für Spannungsteiler auf GPIO19
  resistor_value: "10kOhm"

  # Widerstandswerte
  min_resistance: "1000"
  max_resistance: "50000"

  # On Boot Feuchtigkeitserkennung-Schwellwert
  wet_onboot: "20000"

  #Messintervall
  measure_dry: "5000"
  measure_wet: "30000"
  stabilization: 2sec

esphome:
  name: $name
  platform: ESP32
  board: esp32dev
  onboot:
    then:
      - ....

captive_portal:

ota:

api:

script:

- id: begin_measure
  mode: single
  then:
    - switch.turn_on: resistance_bias
    - delay: $stabilization

  - id: end_measure
    mode: single
    then:
      - switch.turn_off: resistance_bias

  - id: test_resistance
    mode: single
    then:
      - script.execute: begin_measure
      - script.wait: begin_measure

      - if:
          condition:
            lambda: "retun id(resistance_sensore).state < $wet_onboot
          then:
            - script.execute: its_raining
      - script.execute: end_measure
      - script.wait: end_measure

  - id: save_current_resistance
    then:
      - sensor.template.publish:
        id: latest_resistance_sensor
        state: !lamda "return id(resistance_sensore).state;"
